language: node_js
node_js:
  - "0.12"
before_install:
  - sudo apt-get update
# before_script:
#   - cd test
install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - npm install
  - bower install
script:
  - gulp test
